name: SerbleNetworkPlugin
main: net.serble.serblenetworkplugin.Main
version: 1.0
api-version: 1.13
depend: [NickAPI]
softdepend: [PlaceholderAPI]

commands:
  menu:
  lob:
  hub:
  lobby:
  adminmode:
  spawn:
  cosmetic:
  ranknick:
  nick:
  unnick:
  build:
  reloadconfig:
  money:
  store:
  shop:
  sysgivemoney:
  play:
  goto:
  chatsudo:
  serblexp:
  sysgivexp:
  grantachievementprogress:
  profile:
  profileperms:
  serbledebug: